import 'package:myapp/models/match.dart';

class MatchRepository {
  static List<Match> tabela = [
    Match(
        championPlayed: "images/champions/Gnar_0.jpg",
        matchResult: "Win",
        kills: 10,
        deaths: 2,
        assists: 12,
        item1: "images/itens/3181.png",
        item2: "images/itens/3748.png",
        item3: "images/itens/3742.png",
        item4: "images/itens/3075.png",
        item5: "images/itens/3071.png",
        item6: "images/itens/3111.png",
        summonerSpell1: "images/Electrocute.png",
        summonerSpell2: "images/Electrocute.png"),
    Match(
        championPlayed: "images/champions/Zeri_0.jpg",
        matchResult: "Win",
        kills: 10,
        deaths: 2,
        assists: 12,
        item1: "images/itens/3085.png",
        item2: "images/itens/3124.png",
        item3: "images/itens/3156.png",
        item4: "images/itens/3139.png",
        item5: "images/itens/3094.png",
        item6: "images/itens/3508.png",
        summonerSpell1: "images/Electrocute.png",
        summonerSpell2: "images/Electrocute.png"),
    Match(
      championPlayed: "images/champions/Singed_0.jpg",
      matchResult: "Loss",
      kills: 10,
      deaths: 2,
      assists: 12,
      item1: "images/itens/3181.png",
      item2: "images/itens/3748.png",
      item3: "images/itens/3742.png",
      item4: "images/itens/3075.png",
      item5: "images/itens/3071.png",
      item6: "images/itens/3111.png",
      summonerSpell1: "images/Electrocute.png",
      summonerSpell2: "images/Electrocute.png",
    ),
    Match(
        championPlayed: "images/champions/Mordekaiser_0.jpg",
        matchResult: "Loss",
        kills: 10,
        deaths: 2,
        assists: 12,
        item1: "images/itens/3181.png",
        item2: "images/itens/3748.png",
        item3: "images/itens/3742.png",
        item4: "images/itens/3075.png",
        item5: "images/itens/3071.png",
        item6: "images/itens/3111.png",
        summonerSpell1: "images/Electrocute.png",
        summonerSpell2: "images/Electrocute.png"),
  ];
}
